### PR TITLE
Send Summary points in their respective OTLP Summary representation.

### LINKED ISSUE #149: Prometheus Summary conversion is incorrect
The OTLP output for a Prometheus Summary is not properly combining the _sum, _count, and assorted quantiles into a single data point.

### PR DESCRIPTION
**Pull request by carlosalberto**
Fixes #149 

Before we were sending them as a individual metric series/points,
but there's no need to these days.

### CODE REVIEW

File: retrieval/series_cache.go [hunk 1]
```diff
@@ -461,23 +461,9 @@ func (c *seriesCache) lookup(ctx context.Context, ref uint64) (retErr error) {
...
-		default:
-			// Note: this branch has been seen for a
-			// _bucket suffix, indicating a mix of
-			// histogram and summary conventions.
-			failedReason = "invalid_suffix"
-			return errors.Errorf("unexpected summary suffix %q", suffix)
-		}
+		ts.Name = c.getMetricName(c.metricsPrefix, baseMetricName)
+		ts.Kind = config.CUMULATIVE
+		ts.ValueType = config.DOUBLE
```
Comment (carlosalberto) [inline retrieval/series_cache.go:466]: Summary uses ValueType=DISTRIBUTION, while I suspect we need to use DOUBLE for it. Is this correct?

File: retrieval/transform.go [hunk 2]
```diff
@@ -275,6 +277,105 @@ func (d *distribution) Swap(i, j int) {
...
+
+		switch e.suffix {
+		case metricSuffixSum:
+			sum = v
+		case metricSuffixCount:
+			count = v
+			// We take the count series as the authoritative source for the overall reset timestamp.
+			resetTimestamp = rt
+		case "": // Actual values at quantiles.
+			quantile, err := strconv.ParseFloat(e.lset.Get("quantile"), 64)
```
Comment (carlosalberto) [inline retrieval/transform.go:343]: Simply fetching and setting the quantile & value. Do we need to do further conversion? This was not clear from reading the Prometheus docs (in comparison, `le` needs special handling in the case of Histograms).

File: retrieval/transform_test.go [hunk 3]
```diff
@@ -408,81 +432,98 @@ func TestSampleBuilder(t *testing.T) {
...
 			metadata: promtest.MetadataMap{
 				"job1/instance1/metric1": &metadataEntry{Metric: "metric1", MetricType: textparse.MetricTypeSummary, ValueType: config.DOUBLE},
+				"job1/instance1/metric1_a_count": &metadataEntry{Metric: "metric1_a_count", MetricType: textparse.MetricTypeGauge, ValueType: config.DOUBLE},
 			},
 			series: seriesMap{
 				1: labels.FromStrings("job", "job1", "instance", "instance1", "__name__", "metric1_sum"),
 				2: labels.FromStrings("job", "job1", "instance", "instance1", "__name__", "metric1", "quantile", "0.5"),
 				3: labels.FromStrings("job", "job1", "instance", "instance1", "__name__", "metric1_count"),
 				4: labels.FromStrings("job", "job1", "instance", "instance1", "__name__", "metric1", "quantile", "0.9"),
+				// Add another series that only deviates by having an extra label. We must properly detect a new summary.
```
Comment (carlosalberto) [inline retrieval/transform_test.go:442]: Modeled the new tests inspired by the ones exposed by Histogram (replacing the old, simple test cases).

File: retrieval/series_cache.go (hunk 1 above)
Comment (jmacd) [reply retrieval/series_cache.go:466]: The Kind/ValueType distinction in StackDriver vs. OTLP is very very very confusing. It doesn't really matter in this case, since Summary points have a dedicated OTLP point kind.

File: retrieval/transform.go (hunk 2 above)
Comment (jmacd) [reply retrieval/transform.go:343]: I do not believe we need to sort these or process them in any other ways.

**Review by jmacd — APPROVED** [review]

File: retrieval/series_cache.go (hunk 1 above)
Comment (jmacd) [reply retrieval/series_cache.go:466]: (there is room for a whole PR to clean this up, since OTLP is different than SD; the ability to select static metadata would be better if it matched OTLP's terms!)
